CLS
DIM klub$(5)
DIM igry(5)
DIM ochki(5)
DIM sila(5)
klub$(1) = "TCR"
klub$(2) = "Power Buf"
klub$(3) = "FC Roma"
klub$(4) = "Star"
klub$(5) = "Liverts"
sila(1)=
PRINT klub$(1); "       "; igry(1); " игры  "; ochki(1); " очков"
PRINT klub$(2); " "; igry(2); " игры  "; ochki(2); " очков"
PRINT klub$(3); "   "; igry(3); " игры  "; ochki(3); " очков"
PRINT klub$(4); "      "; igry(4); " игры  "; ochki(4); " очков"
PRINT klub$(5); "   "; igry(5); " игры  "; ochki(5); " очков"

